AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spring Cloud Functions.
Resources:
  AwsLambdaFunctionLocal:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aws-lambda-function
      Handler: com.mj.aws.lambda.AwsLambdaFunctionHandler
      Description: For calling sqs lambda function
      Runtime: java8
      CodeUri: ./target/aws-lambda-function-0.0.1-SNAPSHOT-aws.jar
      MemorySize: 320
      Timeout: 120
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: local
